name: MGO-P채ivitys
on:
  schedule:
    - cron: '0 * * * *' # Ajaa p채ivityksen kerran tunnissa
  workflow_dispatch: # Sallii manuaalisen k채ynnistyksen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Aja haku
        run: node scraper.js
      - name: Tallenna muutokset
        run: |
          git config --global user.name "MGO-Bot"
          git config --global user.email "bot@github.com"
          git add data.json
          git commit -m "Automaattinen p채ivitys" || exit 0
          git push
